version: '3.8'
services:
  db:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5440:5432
    volumes: 
      - hub_credits_db:/var/lib/postgresql/data
  
volumes:
  hub_credits_db:
    driver: local