//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::{
    credit_deductions::Entity as CreditDeductions, credit_deposits::Entity as CreditDeposits,
    organization_credits::Entity as OrganizationCredits,
};
