//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0
#![allow(clippy::pedantic)]
pub mod prelude;

pub mod credit_deductions;
pub mod credit_deposits;
pub mod organization_credits;
pub mod sea_orm_active_enums;
